name: "my workflow 1"
on: [push]
jobs:
    Job1:
      name: get_a_secret
      runs-on: ubuntu-latest
      steps:
      - name: get_a_secret
        env: # Or as an environment variable
          super_secret: ${{ secrets.SECRET001 }}
        run: 
            echo $super_secret
