name: "my workflow 1"
on: [push]
jobs:
    Job1:
      name: get_a_secret
      runs-on: ubuntu-latest
      steps:
      - name: get_a_secret
        run:
          echo define a variable
        env: # Or as an environment variable
          super_secret: ${{ secrets.Secret001 }}
