name: "my workflow 1"
on: [push]
jobs:
    Job1:
      name: get_a_secret
      runs-on: ubuntu-latest
      steps:
      - name: get_a_secret
        env: # Or as an environment variable
          super_secret: ${{ secrets.SECRET001 }}
        run: 
            echo "Github will mask secret:"
            echo $super_secret
            echo "do this way to bypass:"
            echo ${{secrets.SECRET001}} | sed 's/./& /g' 

